#!/usr/bin/python3

import sys

def factorize_number(number):
    factors = []
    for i in range(2, number):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors

def factors(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor_pairs = factorize_number(number)
            for p, q in factor_pairs:
                print(f"{number} = {p} * {q}")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    filename = sys.argv[1]
    factors(filename)
